In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [0]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split

In [0]:
model=Sequential()

In [0]:
h1 = model.add(Dense(2,activation="sigmoid",input_dim=3))
h2=model.add(Dense(3,activation="sigmoid"))
o = model.add(Dense(2,activation="linear"))

In [0]:
w1=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
b1=np.array([0.4,0.2])
w2=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
b2=np.array([0.1,0.1,0.2])
w3=np.array([[0.3,0.2],[-0.5,0.5],[0.7,0.2]])
b3=np.array([-0.1,-0.2])

In [0]:
model.set_weights([w1,b1,w2,b2,w3,b3])

In [0]:
input=np.array([[1,0,1]])
target=np.array([[1,0]])

In [0]:
import keras
ad=keras.optimizers.Adam(lr=0.9)
model.compile(loss="mean_squared_error",optimizer=ad,metrics=['accuracy'])

In [37]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.fit(input,target,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 287ms/step - loss: 0.3679 - acc: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 3ms/step - loss: 2.6488 - acc: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.1166 - acc: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3983 - acc: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 0.9408 - acc: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6997 - acc: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 0.2574 - acc: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0504 - acc: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0592 - acc: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 0.1803 - acc: 1.0000


In [41]:
model.get_weights()

[array([[ 0.31567332, -0.37823993],
        [ 0.4       ,  0.1       ],
        [-0.38432673,  0.12176009]], dtype=float32),
 array([0.5156733 , 0.12176009], dtype=float32),
 array([[-0.1869601 ,  0.10499081,  0.7054899 ],
        [-0.09232774, -0.18975715, -0.09995496]], dtype=float32),
 array([0.21014838, 0.00782003, 0.3025566 ], dtype=float32),
 array([[ 0.40160075,  0.11455312],
        [-0.4021685 ,  0.41780692],
        [ 0.8014475 ,  0.11467624]], dtype=float32),
 array([-0.00055412, -0.2835826 ], dtype=float32)]